language: python
python:
    - "2.6"
    - "2.7"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.1
install:
    - pip install Django==$DJANGO
    - pip install django-nose rednose
    - pip install -e . --use-mirrors
script:
  - ./constructor_forms/tests/runtests.sh
